lib/tiny_blog_web/router.ex
defmodule TinyBlogWeb.Router do
  use TinyBlogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TinyBlog.Auth, repo: TinyBlog.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TinyBlogWeb do
    pipe_through :browser

    get       "/", PageController, :index
    resources "/admin", AdminController, only: [:index, :create]
    post      "/texts/:id", TextController, :update
    post      "/entry/:id", EntryController, :update
    get       "/entry/:id", EntryController, :edit
    delete    "/entry/:id", EntryController, :delete
    resources "/sessions",  SessionController, only: [:new, :create, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", TinyBlogWeb do
  #   pipe_through :api
  # end
end

lib/tiny_blog/application.ex
defmodule TinyBlog.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      TinyBlog.Repo,
      # Start the endpoint when the application starts
      TinyBlogWeb.Endpoint
      # Starts a worker by calling: TinyBlog.Worker.start_link(arg)
      # {TinyBlog.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: TinyBlog.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    TinyBlogWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/tiny_blog/entry.ex
  defmodule TinyBlog.Entry do
    use Ecto.Schema
    import Ecto.Changeset

    schema "entries" do
      field :date, :date
      field :text, :string
      field :title, :string

      timestamps()
    end

    @doc false
    def changeset(entry, attrs) do
      entry
      |> cast(attrs, [:title, :text, :date])
      |> validate_required([:title, :text, :date])
    end
  end

lib/tiny_blog/repo.ex
defmodule TinyBlog.Repo do
    use Ecto.Repo,
      otp_app: :tiny_blog,
      adapter: Ecto.Adapters.Postgres
      
end

lib/tiny_blog/text.ex
defmodule TinyBlog.Text do
    use Ecto.Schema
    import Ecto.Changeset

    schema "texts" do
        field :keyword, :string
        field :value, :string
    end

end

lib/tiny_blog/user.ex
defmodule TinyBlog.User do
    use Ecto.Schema
    import Ecto.Changeset

    schema "users" do
        field :username, :string
        field :password, :string

        timestamps()
    end

end

lib/tiny_blog_web/controllers/admin_controller.ex
defmodule TinyBlogWeb.AdminController do
    use TinyBlogWeb , :controller

    import TinyBlogWeb.AuthPlug
    import Ecto.Query   
    alias TinyBlog.Entry
    alias TinyBlog.Repo

    plug :authenticate when action in [:index, :show]

    def index(conn, _params) do
        changeset = Entry.changeset(%Entry{}, %{})
        entries = Entry |> order_by(desc: :id) |> Repo.all()
        text = Repo.get_by(TinyBlog.Text, keyword: "header")
        render(conn, "index.html", changeset: changeset, entries: entries, text: text)
    end

    def create(conn, %{"entry" => entry_params}) do
        changeset = Entry.changeset(%Entry{}, Map.put(entry_params, "date", DateTime.utc_now()))
        {:ok, entry} = Repo.insert(changeset)
        conn
        |> put_flash(:info, "#{entry.title} created!")
        |> redirect(to: Routes.admin_path(conn, :index))
    end

end

lib/tiny_blog_web/controllers/entry_controller.ex
defmodule TinyBlogWeb.EntryController do
    use TinyBlogWeb, :controller
    
    import TinyBlogWeb.AuthPlug
    plug :authenticate when action in [:update, :edit, :delete]
    
    import Ecto.Query   
    alias TinyBlog.Entry
    alias TinyBlog.Repo

    def update(conn, %{"id" => id, "entry" => entry_params}) do
        entry = Repo.get!(TinyBlog.Entry, id)

        entry
        |> Entry.changeset(entry_params)
        |> Repo.update()
        |> case do
            {:ok, _} ->
                conn
                |> put_flash(:info, "Entry updated successfully.")
                |> redirect(to: Routes.admin_path(conn, :index))
            {:error, _} ->
                render(conn, "edit.html", id: id)
        end
    end

    def edit(conn, %{"id" => id}) do
        entry = Repo.get(TinyBlog.Entry, id)
        changeset = Entry.changeset(%Entry{}, %{title: entry.title, text: entry.text})
        
        render(conn, "edit.html", changeset: changeset, entry: entry)
    end

    def delete(conn, %{"id" => id}) do
        entry = Repo.get(TinyBlog.Entry, id)
        Repo.delete(entry)

        redirect(conn, to: Routes.admin_path(conn, :index))
    end
end

lib/tiny_blog_web/controllers/page_controller.ex
defmodule TinyBlogWeb.PageController do
  use TinyBlogWeb, :controller
  alias TinyBlog.Repo

  def index(conn, _params) do
    entries = Repo.all(TinyBlog.Entry)
    headline = Repo.all(TinyBlog.Text)

    render(conn, "index.html", entries: entries)
  end
end

lib/tiny_blog_web/controllers/session_controller.ex
defmodule TinyBlogWeb.SessionController do
  use TinyBlogWeb, :controller
  
  alias TinyBlogWeb.Router.Helpers, as: Routes
  alias TinyBlog.Repo

  import TinyBlogWeb.AuthPlug

  plug :is_authenticated when action in [:new]


  def new(conn, _) do
    render conn, "new.html"
  end

  def create(conn, %{"session" => %{"username" => user, "password" =>
                                     pass}}) do

    case TinyBlog.Auth.login_by_username_and_pass(conn, user,
          pass, repo: Repo ) do

      {:ok, conn} ->
        conn
        |> put_flash(:info, "Welcome back!")
        |> redirect(to: Routes.admin_path(conn, :index))
      {:error, _reason, conn} ->
        conn
        |> put_flash(:error, "Invalid username/password combination")
        |> render("new.html")
    end
  end

  def delete(conn, _) do 
    conn
    |> TinyBlog.Auth.logout()
    |> redirect(to: Routes.page_path(conn, :index))
  end

end

lib/tiny_blog_web/controllers/text_controller.ex
defmodule TinyBlogWeb.TextController do
    use TinyBlogWeb, :controller

    import Ecto.Changeset 
    import Ecto.Query   
    
    alias TinyBlog.Repo
    
    
    def update(conn, %{"id" => id, "value" => value}) do
        Repo.get!(TinyBlog.Text, id)
        |> change(%{value: value})
        |> Repo.update()
        |> case do
            {:ok, _} ->
                conn
                |> put_flash(:info, "Title updated successfully.")
                |> redirect(to: Routes.admin_path(conn, :index))
            {:error, _} ->
                conn
                |> put_flash(:error, "Something went wrong.")
                |> redirect(to: Routes.admin_path(conn, :index))
        end
    
    end
end

lib/tiny_blog_web/views/admin_view.ex
defmodule TinyBlogWeb.AdminView do
  use TinyBlogWeb, :view
end

lib/tiny_blog_web/views/entry_view.ex
defmodule TinyBlogWeb.EntryView do
    use TinyBlogWeb, :view
end

lib/tiny_blog_web/views/error_view.ex
defmodule TinyBlogWeb.ErrorView do
  use TinyBlogWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/tiny_blog_web/views/layout_view.ex
defmodule TinyBlogWeb.LayoutView do
  use TinyBlogWeb, :view
  alias TinyBlog.Repo

  def title do
    text = Repo.get_by(TinyBlog.Text, keyword: "header")
    cond do
      text -> text.value
      true -> "Blog"
    end
  end
end

lib/tiny_blog_web/views/page_view.ex
defmodule TinyBlogWeb.PageView do
  use TinyBlogWeb, :view
end

lib/tiny_blog_web/views/session_view.ex
defmodule TinyBlogWeb.SessionView do
    use TinyBlogWeb, :view
end

lib/tiny_blog_web/templates/entry/edit.html.eex
<%= form_for @changeset, Routes.entry_path(@conn, :update, @entry), fn f -> %>

    Title
    <div class="form-group">
        <%= text_input f, :title, placeholder: "Title", class: "form-control" %>
    </div>

    Text
    <div class="form-group">        
        <%= textarea f, :text, class: "form-control text-area-large"%>
    </div>

    <%= submit "Update", class: "button-small button-green" %>
    <%= link "Go back", to: Routes.admin_path(@conn, :index), class: "link-grey" %>
<% end %>

lib/tiny_blog_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>TinyBlog</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    
 
    <%= if @current_user do %>      
      <div class="row">
        <div class="column column-10 column-offset-90">
          <%= link "Logout", to: Routes.session_path(@conn, :delete, @current_user), method: :delete %>
          <%= link " Home ", to: Routes.page_path(@conn, :index) %>
          <%= link " Admin ", to: Routes.admin_path(@conn, :index) %>
        </div>
      </div>
    <% end %>

      <header class="header">
        <section class="container">

          <h1><%= title() %></h1>          
        </section>
      </header>

    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/tiny_blog_web/templates/page/index.html.eex
<section class="column">
  <article class="column">
   </article>
</section>

<div class="entry-container">
  <%= for entry <- @entries do %>
    <article>
      <h3><%= entry.title%></h3>
        <p><%= entry.text %></p>
        <hr>
      </article>
  <% end %>
</div>

lib/tiny_blog_web/templates/session/new.html.eex
<h1> Login </h1>

<%= form_for @conn, Routes.session_path(@conn, :create), [as: :session], fn f -> %>
  <div class="form-group">
    <%= text_input f, :username, placeholder: "Username", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= password_input f, :password, placeholder: "Password", class: "form-control" %>
  </div>
  <%= submit "Login", class: "btn btn-primary" %>
<%end %>